# NumPy

NumPy is the numerical engine beneath Pandas, scikit-learn, TensorFlow, and PyTorch. Every dataset 
eventually becomes a NumPy array. This chapter builds the mental model you need before touching any 
ML library. 

If previous chapter  was about reading Python, this chapter is about thinking in arrays. Once you can 
comfortably visualize an operation happening across an entire array, not element by element, the 
rest of the ML stack becomes far easier to learn. 

NumPy provides the ndarray-> a fast, fixed-type, multi-dimensional array, plus vectorized math 
operations written in C

Python lists are slow for numeric work because each element is a separate object. NumPy stores data in 
contiguous memory and applies operations to entire arrays at once. 

#AI/ML Use Case 

Every image, audio signal, weight matrix, and gradient in ML is represented as a NumPy array (or a 
library built on the same idea, like a PyTorch tensor

NumPy arrays are homogeneous (single data type) and fixed-size, unlike Python lists ...this is 
exactly why they're fast.

# The ndarray & Creating Arrays

In [1]:
import numpy as np

a= np.array([1,2,3])      # from a list
b = np.array([[1,2],[3,4]])  # 2D array (matrix)
zeros = np.zeros ((2,3))       # 2*3 array of zeros
ones = np.ones((1,3))          # 1*3 array of ones
rng = np.arange(0,10,2)        # [0,2,4,6,8]
lin = np.linspace(0,1,5)       # 5 evenly spaced values between 0 and 1
identity = np.eye(3)           # 3*3 identity matrix

In [2]:
# note - np.arange(0,10,2) starts at 0, adds step 2 each time, stops before 10 → [0, 2, 4, 6, 8]

In [5]:
# more creation helpers

const = np.full((2,2),7)      # array filled with constant value 7
np.empty((2,2))               # to uninitialize the array (fast, but garbage values)
np.array([1,2,3]).copy()      # explicit copy at creation time

array([1, 2, 3])

In [4]:
const

array([[7, 7],
       [7, 7]])

# Datatypes (dtype)

In [6]:
a = np.array([1, 2, 3]) 
a.dtype            # int64 
b = np.array([1.0, 2, 3]) 
b.dtype            # float64 
c = a.astype(np.float32)   # convert type, smaller memory footprint 

#AI/ML Use Case:  Deep learning models often require float32 specifically, using float64 wastes GPU 
memory and slows training.

# Array Attributes 

Attribute          Meaning                        Example 
.shape             Dimensions of the array       (3, 4) → 3 rows, 4 cols 
.ndim              Number of dimensions           2 for a matrix 
.size              Total number of elements       12 for a 3x4 array 
.dtype             Data type of elements          float64

In [8]:
a = np.array([1,2,3,4,5,6])
a[0]
a[-1]
a[1:4]

array([2, 3, 4])

In [10]:
m = np.array([[1,2,3], [4,5,6]]) 
m[0, 1]       # 2   (row 0, col 1) 
m[:, 1]       # [2, 5]  (entire column 1) 
m[1, :]       # [4, 5, 6]  (entire row 1)

array([4, 5, 6])

# Boolean Indexing 
Selecting elements using a condition instead of a position, the foundation of filtering in both NumPy 
and Pandas.

In [11]:
a = np.array([10, 15, 22, 8, 30]) 
mask = a > 15    # [False, False, True, False, True] 
a[mask]          # [22, 30]     
a[a > 15] = 0    # set matching elements to 0

In [12]:
a

array([10, 15,  0,  8,  0])

#AI/ML Use Case 

Filtering outliers, selecting samples of a specific class, or masking invalid values (e.g. negative ages) in 
one line.

# Broadcasting and Vectorization 

Broadcasting lets NumPy apply operations between arrays of different (but compatible) shapes without 
writing loops. Vectorization means applying an operation to a whole array at once. 

In [13]:
a = np.array([1, 2, 3]) 
a * 2                 # [2, 4, 6]  -- scalar broadcast to every element

m = np.array([[1,2,3],[4,5,6]]) 
v = np.array([10, 20, 30]) 
m + v               # v is broadcast across every row     
# [[11,22,33], 
#  [14,25,36]] 

array([[11, 22, 33],
       [14, 25, 36]])

#AI/ML Use Case 

Normalizing every row of a feature matrix by subtracting the column means — done in one broadcasted 
line instead of nested loops

Vectorized NumPy code can be 50-100x faster than an equivalent Python for-loop. Interviewers 
often ask you to vectorize a loop.

# Mathematical Operations & Aggregation

In [14]:
a = np.array([[1,2,3],[4,5,6]]) 
  
a.sum()          # 21 (all elements) 
a.mean()         # 3.5 
a.std()          # standard deviation 
a.max(); a.min() 
a.sum(axis=0)    # column-wise sum -> [5, 7, 9] 
a.sum(axis=1)    # row-wise sum    -> [6, 15] 

array([ 6, 15])

AI/ML Use Case 

axis=0 vs axis=1 is the single most confused — and most tested — NumPy concept. axis=0 collapses rows 
(operates down each column); axis=1 collapses columns (operates across each row).

# Reshape, Flatten & Transpose

In [15]:
a = np.arange(6)            # [0,1,2,3,4,5] 
a.reshape(2, 3)              # [[0,1,2],[3,4,5]] 

  
m = np.array([[1,2,3],[4,5,6]]) 
m.flatten()                  # [1,2,3,4,5,6]  -- always returns a copy 
m.T                          # transpose -> [[1,4],[2,5],[3,6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
a.reshape(-1, 1)             # column vector, -1 means "infer this dimension" 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

#AI/ML Use Case:  

Flattening a 28x28 image into a 784-length vector before feeding it into a model, or 
reshaping predictions to match label shape. 

# Random Module 
AI/ML Use Case:  
Initializing model weights, shuffling datasets, and generating synthetic data for testing pipelines. 

In [19]:
np.random.seed(42)                 # reproducibility 

In [20]:
np.random.rand(3)                  # 3 uniform random floats [0,1) 

array([0.37454012, 0.95071431, 0.73199394])

In [21]:
np.random.randn(3)                 # 3 values from standard normal 

array([-1.11188012,  0.31890218,  0.27904129])

In [22]:
np.random.randint(0, 10, size=5)   # 5 random ints [0,10) 

array([7, 2, 5, 4, 1], dtype=int32)

In [23]:
np.random.choice([1,2,3], size=2)  # random sample 

array([2, 2])

# Basic Linear Algebra

In [25]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [26]:
a.dot(b)     # matrix multiplication

array([[19, 22],
       [43, 50]])

In [27]:
a @ b   # same as dot, preferred modern syntax

array([[19, 22],
       [43, 50]])

In [28]:
np.linalg.inv(a)        # inverse of a

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [29]:
np.linalg.det(a)         # determinant of a

np.float64(-2.0000000000000004)

#AI/ML Use Case

Matrix multiplication (@) is the core operation behind linear regression, neural 
network layers, and similarity computations. 

# Copy vs View 

slicing a numpy array returns a view(shares memory with the original) by default, not a copy.

Modifying a view changes the original array

In [31]:
a = np.array([1,2,3,4,5])

b = a[0:3]    # view -- shares memory with a

In [33]:
b

array([1, 2, 3])

In [34]:
b[0] = 99

In [36]:
a         # a changed too

array([99,  2,  3,  4,  5])

In [37]:
# explicit copy -- safe, independent
c = a[0:3].copy()
c

array([99,  2,  3])

#  Stacking & Splitting Arrays
Combining multiple arrays into one (stacking) or breaking one array into multiple pieces (splitting) — 
common when assembling batches or features.

In [38]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.vstack([a,b])


array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [48]:
m = np.array([[1,2,3,4],[5,6,7,8]])

In [49]:
np.split(m,2,axis = 1) 

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

#AI/ML Use Case 

Combining feature arrays from multiple sources into one matrix, or splitting a dataset array into 
train/validation chunks.

# Sorting & Searching

In [50]:
a = np.array([30,10,20])

np.sort(a)  

array([10, 20, 30])

In [52]:
np.argsort(a)     # indices that would sort the array

array([1, 2, 0])

In [53]:
np.argmax(a)     # index of max value

np.int64(0)

In [54]:
 np.argmin(a)    # index of min value

np.int64(1)

In [55]:
np.where(a>15)    # indices where condition is True

(array([0, 2]),)

#AI/ML Use Case 

np.argmax() is used constantly to convert model output probabilities into a predicted class index (e.g. 
np.argmax(probs, axis=1)).

np.where(condition, x, y) can also act like a vectorized if-else: it returns x where the condition is 
True, y otherwise.

# Handling NaN in Numpy

np.nan represents a missing/undefined float value. 

It behaves unusually: it is never equal to anything, 
including itself.

In [57]:
a = np.array([1, np.nan, 3])
a

array([ 1., nan,  3.])

In [58]:
np.isnan(a)   

array([False,  True, False])

In [59]:
np.nanmean(a)        # mean ignoring nan

np.float64(2.0)

In [63]:
# to filter out NaN values
a[np.isnan(a) == False]

# another way to write is using predicate logic, negation sign
a[~np.isnan(a)]

array([1., 3.])

Common Mistakes

Mistake:  Using a == np.nan to check for missing values — this always returns False. Use np.isnan(a) or 
pd.isna() instead

# Fancy Indexing
Indexing an array using a list or array of indices, rather than a single index or slice — lets you select an 
arbitrary, non-contiguous set of elements. 

In [64]:
a = np.array([10, 20, 30, 40, 50]) 
idx = [0, 2, 4] 
a[idx]            
# [10, 30, 50] 

array([10, 30, 50])

In [65]:
m = np.array([[1,2],[3,4],[5,6]]) 
m[[0, 2]]         
# rows 0 and 2 -> [[1,2],[5,6]]

array([[1, 2],
       [5, 6]])

#AI/ML Use Case 

Selecting a specific random subset of rows for a train/validation split, given a list of shuffled indices

# Performance Benefits 
NumPy operations run in compiled C code, use contiguous memory blocks, and avoid Python's per
object overhead. In practice, this means: 


• Vectorized operations replace explicit Python loops 

• Memory usage is lower, fixed-type arrays vs. heterogeneous Python objects 

• Operations scale to millions of rows, which is essential for real datasets 

Interview Tips

If asked 'why is NumPy faster than lists', mention: contiguous memory, fixed dtype, and 
vectorized C-level loops — not just 'it's optimized'. 

# Worked Example : Linear Regression by Hard

In [66]:
X = np.array([1,2,3,4,5])
y = np.array([2,4,5,4,5])

In [67]:
x_mean, y_mean = X.mean(), y.mean()

In [68]:
# slope (m) and intercept (b) using the least - squares formula

In [69]:
m = np.sum((X-x_mean) *( y-y_mean))/ np.sum((X-x_mean)**2)

b = y_mean -m * x_mean

predictions = m*X+b

In [70]:
predictions

array([2.8, 3.4, 4. , 4.6, 5.2])

Every single piece of this — mean(), broadcasting (X - x_mean), element-wise multiplication, and sum() 
is something covered in this chapter. This is exactly the math scikit-learn's LinearRegression runs 
internally, just wrapped in a friendlier interface. 

Interview Tip:  Being able to derive linear regression with raw NumPy is a strong interview signal 
,it shows you understand what the library is actually doing, not just how to call .fit().

# Practice Exercises

1. Create a 5x5 array of random integers between 1-100, then find the row with the highest sum.

In [72]:
a = np.random.randint(1,100, size=(5,5))

In [73]:
a

array([[ 2, 64, 60, 21, 33],
       [76, 58, 22, 89, 49],
       [91, 59, 42, 92, 60],
       [80, 15, 62, 62, 47],
       [62, 51, 55, 64,  3]], dtype=int32)

In [75]:
rows_sum = a.sum(axis = 1)
rows_sum

array([180, 294, 344, 266, 235])

In [77]:
best_row = np.argmax(rows_sum)
best_row

np.int64(2)

2. Given an array of exam scores, replace any score below 40 with 40 (a floor).

In [79]:
scores = np.array([10,30,40,50,60,70,80,90])
scores[scores < 40] = 40
scores

array([40, 40, 40, 50, 60, 70, 80, 90])

3. Standardize an array (subtract mean, divide by std) without using any loop.

In [80]:
a = np.array([10,20,30,40])
standardized = (a-a.mean() / a.std())

4. Given a 1D array of 12 values, reshape it into a (3,4) matrix and then transpose it.

In [82]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
a.reshape(3,4).T

# you can even use .transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])